"""Emit an idempotent D1 backfill for canonical Gym and Bank brands.

Run after migrations/0010_brand_aware_nearby.sql, without re-importing the
country dataset:

  python3 cloudflare/extraction/backfill_brands.py > /tmp/brand-backfill.sql
  cd cloudflare && npx wrangler d1 execute brush-poi-registry --remote --file=/tmp/brand-backfill.sql

The canonical values and aliases come directly from the shared app/import/API
catalogue. A matching update always writes the canonical `name`; unmatched
Gym/Bank records become NULL, which is intentional and makes the script safe
to rerun after the catalogue grows.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DICTIONARY_PATH = os.path.join(ROOT, 'src', 'constants', 'brandDictionary.json')


def sql_string(value):
    return "'" + value.replace("'", "''") + "'"


def brand_case(entries):
    clauses = []
    for entry in entries:
        for alias in [entry['name'], *entry.get('aliases', [])]:
            clauses.append(f"WHEN name LIKE {sql_string('%' + alias + '%')} THEN {sql_string(entry['name'])}")
    return '\n      '.join(clauses)


def emit_for_foursquare(poi_type, entries):
    print(f"""UPDATE poi
SET brand = CASE
      {brand_case(entries)}
      ELSE NULL
    END
WHERE EXISTS (
  SELECT 1 FROM poi_type
  WHERE poi_type.fsq_place_id = poi.fsq_place_id
    AND poi_type.poi_type = {sql_string(poi_type)}
);""")


def emit_for_curated(poi_type, entries):
    print(f"""UPDATE curated_poi
SET brand = CASE
      {brand_case(entries)}
      ELSE NULL
    END
WHERE primary_poi_type = {sql_string(poi_type)};""")


def main():
    with open(DICTIONARY_PATH) as source:
        dictionary = json.load(source)
    print('-- Generated by extraction/backfill_brands.py. Do not hand-edit.')
    for poi_type in ('gym', 'bank'):
        entries = dictionary[poi_type]
        emit_for_foursquare(poi_type, entries)
        emit_for_curated(poi_type, entries)
    print("""-- Backfill report: capture these result rows with the deployment record.
SELECT poi_type.poi_type, poi.brand, COUNT(*) AS places
FROM poi_type
JOIN poi ON poi.fsq_place_id = poi_type.fsq_place_id
WHERE poi_type.poi_type IN ('gym', 'bank')
GROUP BY poi_type.poi_type, poi.brand
ORDER BY poi_type.poi_type, places DESC, poi.brand;

SELECT primary_poi_type AS poi_type, brand, COUNT(*) AS places
FROM curated_poi
WHERE primary_poi_type IN ('gym', 'bank')
GROUP BY primary_poi_type, brand
ORDER BY primary_poi_type, places DESC, brand;""")


if __name__ == '__main__':
    main()
