import { Container } from '@cloudflare/containers';
import type { Env } from './index';

/**
 * KAN-354 — the extraction pipeline (Python + DuckDB, cloudflare/extraction/)
 * as a Cloudflare Container instead of a separate GCP service. Same
 * account, same `wrangler deploy`, no second cloud bill (see
 * cloudflare/deploy/README.md — this replaced an earlier GCP Cloud Run Job design
 * once the actual cost/complexity of running two platforms for one
 * pipeline was weighed against just using what Workers Paid already
 * includes).
 *
 * Batch job, not a web server — `run_job.py` runs to completion and exits,
 * so this class never sets `defaultPort` and the Worker always calls
 * `.start()` (fire-and-forget), never `.fetch()`/`startAndWaitForPorts()`.
 *
 * `sleepAfter` is generous (country mode can run up to ~an hour, no latency
 * target per docs/poi-coverage-model.md) — this bounds how long an
 * unexpectedly-hung process gets before Cloudflare kills the instance, not
 * a normal-case timeout.
 */
export class ExtractionContainer extends Container<Env> {
  sleepAfter = '90m';
  enableInternet = true; // must reach the Foursquare Iceberg catalog + Nominatim

  /**
   * Lets the container's Python code reach D1 and R2 through the Worker's
   * own bindings (a plain HTTP request to a fake hostname, translated here)
   * instead of holding a separate Cloudflare API token or R2 S3 access
   * keys — see cloudflare/extraction/d1_client.py / r2_client.py. Runs
   * inside the Workers runtime, not the container sandbox — env is this
   * Worker's own env, the same REGISTRY_DB/POI_EXPORTS bindings index.ts uses.
   */
  static outboundByHost = {
    // POST http://d1.internal/  { sql }  — always .run(), never .all(): the
    // pipeline only ever executes DML (INSERT/UPDATE/DELETE) against D1,
    // generated by classify_and_load.py — it has no reason to SELECT.
    'd1.internal': async (request: Request, env: Env): Promise<Response> => {
      if (request.method !== 'POST') {
        return new Response(JSON.stringify({ success: false, error: 'method not allowed' }), { status: 405 });
      }
      let body: { sql?: unknown };
      try {
        body = await request.json();
      } catch {
        return new Response(JSON.stringify({ success: false, error: 'invalid JSON body' }), { status: 400 });
      }
      if (typeof body.sql !== 'string' || !body.sql.trim()) {
        return new Response(JSON.stringify({ success: false, error: 'sql must be a non-empty string' }), { status: 400 });
      }
      try {
        const result = await env.REGISTRY_DB.prepare(body.sql).run();
        return new Response(JSON.stringify({ success: true, meta: result.meta }), { status: 200 });
      } catch (err) {
        return new Response(JSON.stringify({ success: false, error: String(err) }), { status: 500 });
      }
    },

    // PUT http://r2.internal/<percent-encoded key>  (raw body)  — uploads
    // one object. GET isn't implemented — nothing in the pipeline needs to
    // read back from R2, only write extracts/exports to it.
    'r2.internal': async (request: Request, env: Env): Promise<Response> => {
      if (request.method !== 'PUT') {
        return new Response('method not allowed', { status: 405 });
      }
      let key: string;
      try {
        key = decodeURIComponent(new URL(request.url).pathname.slice(1));
      } catch {
        return new Response('key is not validly percent-encoded', { status: 400 });
      }
      if (!key) {
        return new Response('key is required', { status: 400 });
      }
      await env.POI_EXPORTS.put(key, request.body);
      return new Response('ok', { status: 200 });
    },
  };
}
